services:
  postgres:
    image: postgres:13.10-alpine
    container_name: warehouse-control-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: warehouse_control_user
      POSTGRES_PASSWORD: warehouse_control_password
      POSTGRES_DB: warehouse_control_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 2s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/init:/docker-entrypoint-initdb.d:ro
      - ./migrations:/migrations:ro
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: warehouse-control-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HTTP_PORT: "8080"
      LOG_LEVEL: "info"
      JWT_SECRET: "oXzXAjJU0xOuUBtLSfd+zuSU5Xyf1T9wad/IiTrhPT3tri5+cXz1tK7Nizzp7a5lERKKkprGAuZmKYCicbNyQQ" # FIXME: JUST FOR DEMO
      DB_DSN: "postgres://warehouse_control_user:warehouse_control_password@postgres:5432/warehouse_control_db?sslmode=disable"
      DB_MAX_OPEN_CONNS: 10
      DB_MAX_IDLE_CONNS: 2
    ports:
      - "8080:8080"

volumes:
  postgres_data: